import sqlite3
con=sqlite3.connect("mydatabase.db")
cur=con.cursor()
#cur.execute("create table if not exists  students(name varchar(50),roll no varchar(50),sec varchar(50))")
#cur.execute('insert into students values("trisha","101","A")')
#cur.execute('insert into students values("kanna","ID512","B")')
#cur.execute('insert into students values("kushi","ID515","B")')
#cur.execute('delete from students where name="trisha"')
cur.execute('update students set name="trisha" where name="kanna"')
x=cur.execute('select *from students')
print(x.fetchall())
#x=cur.execute('show tables')

con.commit()
print(x)